name: Daily Auto Commit

on:
  schedule:
    - cron: "10 13 * * *"  # Runs at 1:10 PM UTC (8:10 AM EST)
  workflow_dispatch:  # Allows manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures the full repo history is available

      - name: Set up Git user
        run: |
          git config --global user.name "vamsiram7"
          git config --global user.email "vpatiban@gmu.edu"

      - name: Pull latest changes
        run: |
          git pull origin main --rebase  # Pulls latest updates before committing

      - name: Make 10 unique commits
        run: |
          for i in {1..10}; do
            echo "Commit $i - $(date)" >> commit_log.txt  # Modify a file uniquely
            git add commit_log.txt
            git commit -m "Automated commit #$i on $(date)" || echo "No changes to commit"
            sleep 2  # Ensures commits are separate
          done

      - name: Merge latest changes
        run: |
          git pull origin main --rebase  # Merge latest changes before pushing

      - name: Push changes
        run: |
          git push origin main
