name: Daily Auto Commit

on:
  schedule:
    - cron: "10 13 * * *"  # Runs at 1:10 PM UTC (8:10 AM EST)
  workflow_dispatch:  # Allows manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Make 10 unique commits
        run: |
          for i in {1..10}; do
            echo "Commit $i - $(date)" >> commit_log.txt  # Modify a file uniquely
            git add commit_log.txt
            git commit -m "Automated commit #$i on $(date)" || echo "No changes to commit"
            sleep 2  # Ensures commits are separate
          done

      - name: Push changes
        run: |
          git push origin main
