name: Daily Auto Commit

on:
  schedule:
    - cron: "0 9 * * *"  # Runs at 9:00 AM UTC daily
  workflow_dispatch:  # Allows manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Make 10 unique commits
        run: |
          for i in {1..10}; do
            # Create a unique file with distinct content for each commit
            echo "This is update #$i with unique content for commit $i" > "update_$i.txt"
            git add "update_$i.txt"
            git commit -m "Automated commit #$i on $(date)"
            git push origin main  # Push to the main branch
            sleep 3  # Small delay to make each commit unique
          done
